
services:
  mrmanoelstore:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SenhaSuper@Segura123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
