// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mr.ManoelStore.Infra;

#nullable disable

namespace Mr.ManoelStore.Infra.Persistence.Migrations
{
    [DbContext(typeof(MrManoelStoreDbContext))]
    [Migration("20250601031959_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mr.ManoelStore.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "pedido_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.HasKey("PedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Mr.ManoelStore.Models.Pedido", b =>
                {
                    b.OwnsMany("Mr.ManoelStore.Models.Produto", "Produtos", b1 =>
                        {
                            b1.Property<int>("PedidoId")
                                .HasColumnType("int");

                            b1.Property<string>("ProdutoId")
                                .HasColumnType("nvarchar(450)")
                                .HasAnnotation("Relational:JsonPropertyName", "produto_id");

                            b1.HasKey("PedidoId", "ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.OwnsOne("Mr.ManoelStore.Models.Dimensoes", "Dimensoes", b2 =>
                                {
                                    b2.Property<int>("ProdutoPedidoId")
                                        .HasColumnType("int");

                                    b2.Property<string>("ProdutoId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<int>("Altura")
                                        .HasColumnType("int");

                                    b2.Property<int>("Comprimento")
                                        .HasColumnType("int");

                                    b2.Property<int>("Largura")
                                        .HasColumnType("int");

                                    b2.HasKey("ProdutoPedidoId", "ProdutoId");

                                    b2.ToTable("Produtos");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "dimensoes");

                                    b2.WithOwner()
                                        .HasForeignKey("ProdutoPedidoId", "ProdutoId");
                                });

                            b1.Navigation("Dimensoes")
                                .IsRequired();
                        });

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
